name: C++ Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Run tests
        run: |
          cd build
          ctest --verbose